Fix PR limit fix to check for schema files changes

diff --git a/.github/workflows/limit-pr-files-changed.yml b/.github/workflows/limit-pr-files-changed.yml
--- a/.github/workflows/limit-pr-files-changed.yml
+++ b/.github/workflows/limit-pr-files-changed.yml
@@ -49,8 +49,7 @@ jobs:
         id: lines_changed_per_file
         run: |
           # Define the maximum allowed lines changed per file
-          JAVA_MAX_LINES=500
-          SCHEMA_MAX_LINES=1500
+          MAX_LINES=500
           MAX_TOTAL_LINES_ADDED=2000
           TOTAL_LINED_ADDED=0
           # Get the diff of the PR and process each file
@@ -76,31 +75,27 @@ jobs:
 
           echo "File: $file, Lines Changed: $TOTAL"
 
-          # Check if the total exceeds the max allowed
-          if [ "$JAVA_FILE" = "true" ]; then
-            MAX_LINES=$JAVA_MAX_LINES
-          elif [ "$SCHEMA_FILE" = "true" ]; then
-            MAX_LINES=$SCHEMA_MAX_LINES
+          # Fail if there are both schema and Java file changes
+          if [[ "JAVA_FILE" == true && "SCHEMA_FILE" == true ]]; then
+            echo "The PR has both schema and Java code changes, please make a separate PR for schema changes."
+            exit 1
           fi
           
-          if [ "$TOTAL" -gt "$MAX_LINES" ]; then
+          if [[ "$TOTAL" -gt "$MAX_LINES" && "$JAVA_FILE" == "true" ]]; then
             echo "File $file exceeds the maximum allowed lines changed ($TOTAL > $MAX_LINES)"
             EXCEEDED=true
           fi
           done < <(git diff --numstat origin/main | grep -E '\.(java|avsc|proto)$')
 
-          # Fail if there are both schema and Java file changes
+          # Fail if total line added exceeds max limit
           if [ "$TOTAL_LINED_ADDED" -gt "$MAX_TOTAL_LINES_ADDED" ]; then
             echo "Total added lines of all files exceed the maximum allowed lines ($TOTAL_LINED_ADDED > $MAX_TOTAL_LINES_ADDED)."
             exit 1
           fi
+          
+          # Fail if total number of lines added exceeds max limit
           if [ "$EXCEEDED" = true ]; then
             echo "Above files exceed the maximum allowed lines changed ($MAX_LINES)."
-            exit 1
-          fi
-          # Fail if any file exceeded the limit
-          if [[ "JAVA_FILE" == true && "SCHEMA_FILE" == true ]]; then
-            echo "The PR has both schema and Java code changes, please make a separate PR for schema changes."
             exit 1
           fi
 
