Check all stages pass in unit test (#1299)
* Check all stages pass in unit test
Even if we have unit test failure, we are able to merge the PR as the last state gets skipped. This PR tries to explicit fail the final completion stage if there are failures in the previous stage.



---------

Co-authored-by: Sourav Maji <tester@linkedin.com>

diff --git a/.github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml b/.github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
--- a/.github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
+++ b/.github/workflows/VeniceCI-StaticAnalysisAndUnitTests.yml
@@ -106,11 +106,25 @@ jobs:
     runs-on: ubuntu-latest
     needs: [ValidateGradleWrapper, StaticAnalysis, UnitTestsAndCodeCoverage]
     timeout-minutes: 120
+    if: success() || failure()  # Always run this job, regardless of previous job status
     steps:
-      - name: AllIsWell
-        shell: bash
+      - name: Check previous job statuses
         run: |
-          echo "LGTM!"
+         if [ "${{ needs.ValidateGradleWrapper.result }}" != "success" ]; then
+          echo "ValidateGradleWrapper failed."
+          exit 1
+         fi
+         if [ "${{ needs.StaticAnalysis.result }}" != "success" ]; then
+          echo "StaticAnalysis failed."
+          exit 1
+         fi
+         if [ "${{ needs.UnitTestsAndCodeCoverage.result }}" != "success" ]; then
+          echo "UnitTestsAndCodeCoverage failed."
+          exit 1
+         fi
+      # If all previous jobs were successful, proceed
+      - name: Final Completion Check
+        run: echo "All checks passed successfully!"
 
 
 
